#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the staircase function below.
def staircase(n):
    i=0
    j=0
    num=n-2
    for i in range(1, n):
        print (' ' * num, '#' * i)
        num -= 1
    print( '#' * n)
    
if __name__ == '__main__':
    n = int(input())

    staircase(n)
